# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'ChatApp-pool'  # Use the name of your self-hosted agent pool
  demands:
  - agent.name -equals backend-agent  # Optional, if you want to target a specific agent

variables:
  BACKEND_VM: '172.168.24.7'
  BACKEND_USER: 'azureuser'
  REPO_URL: 'https://github.com/Hrituj-Bansod/ChatApp.git'
  #WORKSPACE: '$(System.DefaultWorkingDirectory)'
  WORKSPACE:  '/home/azureuser/myagent/_work/chatappcode'
steps:

- script: |
    echo "Removing existing code"
    rm -rf "/home/azureuser/myagent/_work/chatappcode/"
    echo "Cloning Repository"
    git clone -b main $(REPO_URL) $(WORKSPACE)
  displayName: 'Cloning Repository'

- script: |
    echo "Copying Code to Remote Server"
    rsync -az $(WORKSPACE) $(BACKEND_USER)@$(BACKEND_VM):/tmp
  displayName: 'Copying Code to Remote Server'

- script: |
    echo "Stopping Application"
    ssh $(BACKEND_USER)@$(BACKEND_VM) 'sudo systemctl stop chatapp.service'
  displayName: 'Stopping Application'

- script: |
    echo "Copying fundoo file to Actual Location"
    ssh $(BACKEND_USER)@$(BACKEND_VM) 'cp -rf /tmp/ChatApplication/fundoo /new_chatapp'
  displayName: 'Copying fundoo file to Actual Location'

- script: |
    echo "Copying requirements.txt to Actual Location"
    ssh $(BACKEND_USER)@$(BACKEND_VM) 'cp -rf /tmp/ChatApplication/requirements.txt /new_chatapp'
  displayName: 'Copying requirements.txt to Actual Location'

- script: |
    echo "Installing requirements.txt"
    ssh $(BACKEND_USER)@$(BACKEND_VM) 'source /new_chatapp/venv/bin/activate && cd /new_chatapp && pip3 install -r requirements.txt'
  displayName: 'Installing requirements.txt'

- script: |
    echo "Making Migrations"
    ssh $(BACKEND_USER)@$(BACKEND_VM) 'source /new_chatapp/venv/bin/activate && cd /new_chatapp && python3 manage.py makemigrations && python3 manage.py migrate'
  displayName: 'Making Migrations'

- script: |
    echo "Starting Application"
    ssh $(BACKEND_USER)@$(BACKEND_VM) 'sudo systemctl start chatapp.service'
  displayName: 'Starting Application'